### ISSUE TITLE
Usage of /rmcurrency - sometimes kicked

### ISSUE THREAD

**Issue by F3UR10** [inlife/eco-no-player-credits#1]
Hi,

if I use the command /rmcurrency XYZ it removes the currency but sometime (2/3 removed currencies) I got kicked from the server.

Below the test from the dump file:

`--BEGIN DUMP--
Dump Time
02/10/2019 20:43:30

Exception
Exception: ArgumentException
Message:At least one object must implement IComparable.
Source:mscorlib

System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

--END DUMP--`

**Comment by inlife** [comment]
Hello,

I would strongly recommend against using that command since even from my experience it's quite unstable. And unfortunately, I haven't found a solution yet on how to fix that.

**Comment by inlife** [comment]
pushed a new version to the eco-mods site, try it out, check if it helps
